In [1]:
import pandas as pd
from difflib import SequenceMatcher

In [2]:
def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [3]:
left_data_path = '../data/left_dataset.csv'
right_data_path = '../data/right_dataset.csv'
left_data = pd.read_csv(left_data_path)
right_data = pd.read_csv(right_data_path)

In [4]:
left_data.dropna(inplace=True)
right_data.dropna(inplace=True)
print("Missing values in left_df:")
print(left_data.isnull().sum())

print("Missing values in right_data:")
print(right_data.isnull().sum())

Missing values in left_df:
entity_id      0
name           0
address        0
city           0
state          0
postal_code    0
categories     0
dtype: int64
Missing values in right_data:
business_id    0
name           0
address        0
city           0
state          0
zip_code       0
size           0
dtype: int64

In [5]:

#change all name and address to string and be lowercase
left_data['name'] = left_data['name'].astype(str).str.lower()
left_data['address'] = left_data['address'].astype(str).str.lower()
right_data['name'] = right_data['name'].astype(str).str.lower()
right_data['address'] = right_data['address'].astype(str).str.lower()
#remove punctuation
left_data['postal_code'] = left_data['postal_code'].astype(str).apply(lambda x: x.split('.')[0])
right_data['zip_code'] = right_data['zip_code'].astype(str).apply(lambda x: x.split('-')[0])

In [6]:
left_data['block_key'] = left_data['name'].str[:2] + left_data['address'].str[0] + left_data['state'] + left_data['postal_code'].str[:3]
right_data['block_key'] = right_data['name'].str[:2] + right_data['address'].str[0] + right_data['state'] + right_data['zip_code'].str[:3]

In [7]:
merged = pd.merge(left_data, right_data, on='block_key', how='inner', suffixes=('_left', '_right'))

In [8]:
merged.head()

,entity_id,name_left,address_left,city_left,state_left,postal_code,categories,block_key,business_id,name_right,address_right,city_right,state_right,zip_code,size
0,1,the ups store,87 grasso plaza shopping center,Affton,MO,63123,"Shipping Centers, Local Services, Notaries, Ma...",th8MO631,37027,the art of entertaining inc,8796 big bend blvd,SAINT LOUIS,MO,63119,25.0
1,1,the ups store,87 grasso plaza shopping center,Affton,MO,63123,"Shipping Centers, Local Services, Notaries, Ma...",th8MO631,37156,"the kohn partnership, llp",8251 maryland ave suite 108,SAINT LOUIS,MO,63105,9.0
2,1,the ups store,87 grasso plaza shopping center,Affton,MO,63123,"Shipping Centers, Local Services, Notaries, Ma...",th8MO631,37159,the schechter law firm pc,8000 maryland ave ste 950,Saint Louis,MO,63105,9.0
3,1,the ups store,87 grasso plaza shopping center,Affton,MO,63123,"Shipping Centers, Local Services, Notaries, Ma...",th8MO631,37162,"the schechter law firm, p.c.",8000 maryland suite 950,ST LOUIS,MO,63105,9.0
4,1,the ups store,87 grasso plaza shopping center,Affton,MO,63123,"Shipping Centers, Local Services, Notaries, Ma...",th8MO631,37221,"thomas l. dowell & associates, inc.",8460 watson rd suite 141,SAINT LOUIS,MO,63119,7.0

In [9]:
merged['name_similarity'] = merged.apply(lambda x: similar(x['name_left'], x['name_right']), axis=1)
merged['address_similarity'] = merged.apply(lambda x: similar(x['address_left'], x['address_right']), axis=1)

In [10]:
confidence = 0.5 * merged['name_similarity'] + 0.5 * merged['address_similarity']
merged['confidence'] = confidence
filtered_merged = merged[merged['confidence'] > 0.8]
print(filtered_merged[['entity_id', 'business_id', 'confidence']])

         entity_id  business_id  confidence
581             57        32737    0.900000
749             67        77383    0.954545
907             77        28232    0.908163
976             79        62397    0.966667
1028            82        68048    0.827586
...            ...          ...         ...
1132458      94475         2373    0.935897
1132513      94480        77995    0.800680
1133210      94539        79363    0.875000
1133249      94546        83310    0.937500
1133768      94579        80357    0.866944

[7534 rows x 3 columns]

In [13]:
high_confidence_matches = filtered_merged.rename(columns={'entity_id': 'left_dataset', 'business_id': 'right_dataset', 'confidence': 'confidence_score'})
output_columns = ['left_dataset', 'right_dataset', 'confidence_score']
high_confidence_matches[output_columns]

         left_dataset  right_dataset  confidence_score
581                57          32737          0.900000
749                67          77383          0.954545
907                77          28232          0.908163
976                79          62397          0.966667
1028               82          68048          0.827586
...               ...            ...               ...
1132458         94475           2373          0.935897
1132513         94480          77995          0.800680
1133210         94539          79363          0.875000
1133249         94546          83310          0.937500
1133768         94579          80357          0.866944

[7534 rows x 3 columns]

In [15]:
high_confidence_matches[output_columns].to_csv('../data/difflib_submission.csv', index=False)